// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_Pintor.cpp"
#include "EWIEGA46WW/moc_localserver.cpp"
#include "EWIEGA46WW/moc_servertest.cpp"
#include "EWIEGA46WW/moc_widget.cpp"
